# To use:
#
#     pre-commit run -a
#
# Or:
#
#     pre-commit install  # (runs every time you commit in git)
#
# To update this file:
#
#     pre-commit autoupdate
#
# See https://github.com/pre-commit/pre-commit

repos:
  # Standard hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: &excludes |
          (?x)^(
              .*\.blend|
              .*\.dae|
              .*\.mtl|
              .*\.obj|
              .*\.pgm|
              .*\.step|
              .*\.stl
          )$
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        exclude: *excludes
      - id: trailing-whitespace
        exclude: *excludes

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8.git
    rev: 5.0.4
    hooks:
    - id: flake8

  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.11.0
    hooks:
    - id: markdownlint

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.1
    hooks:
      - id: insert-license
        files: \.py$
        exclude: |
          (?x)^(
              .*setup\.py|
              .*__init__\.py
          )$
        args:
          - --license-filepath
          - LICENSE

  - repo: local
    hooks:
      - id: catkin_lint
        name: catkin_lint
        description: Check package.xml and cmake files
        entry: catkin_lint .
        language: system
        always_run: true
        pass_filenames: false
        args: [ "--strict", "--ignore", "UNINSTALLED_SCRIPT" ]
