#! /usr/bin/env python3

import sys
import rospy
import actionlib

from grasplan.msg import InsertObjectAction, InsertObjectGoal

if __name__ == '__main__':
    rospy.init_node('insert_object_action_client')
    if len(sys.argv) > 1:
        if sys.argv[1] != '__ns:=mobipick':
            rospy.logwarn('have you run this node without the mobipick as namespace? if so, it might not work!')

        myargv = rospy.myargv()
        if len(myargv) != 3:
            rospy.logfatal(f'Usage: {myargv[0]} support_surface_name observe_before_placing')
            sys.exit(1)
        support_surface_name = myargv[1]
        if myargv[2] == 'true' or myargv[2] == 'True':
            observe_before_insert = True
        elif myargv[2] == 'false' or myargv[2] == 'False':
            observe_before_insert = False
    else:
        rospy.logwarn('you have run this node without arguments, at least the mobipick namespace is expected! ( __ns:=mobipick )')
    timeout = 50.0 # in seconds, default: 50.0
    insert_object_server_name = 'insert_object'
    action_client = actionlib.SimpleActionClient(insert_object_server_name, InsertObjectAction)
    rospy.loginfo(f'waiting for {insert_object_server_name} action server')
    if action_client.wait_for_server(timeout=rospy.Duration.from_sec(10.0)):
        rospy.loginfo(f'found {insert_object_server_name} action server')
        goal = InsertObjectGoal()
        goal.support_surface_name = support_surface_name
        goal.observe_before_insert = observe_before_insert
        rospy.loginfo(f'sending insert goal to {insert_object_server_name} action server')
        action_client.send_goal(goal)
        rospy.loginfo(f'waiting for result from {insert_object_server_name} action server')
        if action_client.wait_for_result(rospy.Duration.from_sec(timeout)):
            result = action_client.get_result()
            rospy.loginfo(f'{insert_object_server_name} is done with execution, resuĺt was = "{result}"')
            if result.success == True:
                rospy.loginfo(f'Succesfully insertd object')
            else:
                rospy.logerr(f'Failed to insert object')
        else:
            rospy.logerr(f'Failed to insert object, timeout?')
    else:
        rospy.logerr(f'action server {insert_object_server_name} not available')
