#!/usr/bin/env python3

import sys
from rqt_gui.main import Main

plugin = 'grasplan.rqt_planning_scene.rqt_planning_scene.RqtPlanningScene'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
