planning_scene_boxes:
- scene_name: 'table'
  frame_id: 'world'
  box_x_dimension: 0.8
  box_y_dimension: 1.4
  box_z_dimension: 1.02
  box_position_x: 0.0
  box_position_y: 1.2
  box_position_z: 0.51
  box_orientation_x: 0.0
  box_orientation_y: 0.0
  box_orientation_z: 0.0
  box_orientation_w: 1.0
- scene_name: 'conveyor_belt_a'
  frame_id: 'world'
  box_x_dimension: 0.7
  box_y_dimension: 3.3
  box_z_dimension: 0.9
  box_position_x: 0.8
  box_position_y: 1.61
  box_position_z: 0.5
  box_orientation_x: 0.0
  box_orientation_y: 0.0
  box_orientation_z: 0.0
  box_orientation_w: 1.0
- scene_name: 'conveyor_belt_b'
  frame_id: 'world'
  box_x_dimension: 0.7
  box_y_dimension: 3.3
  box_z_dimension: 0.9
  box_position_x: -0.8
  box_position_y: 1.61
  box_position_z: 0.5
  box_orientation_x: 0.0
  box_orientation_y: 0.0
  box_orientation_z: 0.0
  box_orientation_w: 1.0
- scene_name: 'insole_rejection_box'
  frame_id: 'world'
  box_x_dimension: 0.87
  box_y_dimension: 0.59
  box_z_dimension: 0.68
  box_position_x: 0.8
  box_position_y: -0.3
  box_position_z: 0.34
  box_orientation_x: 0.0
  box_orientation_y: 0.0
  box_orientation_z: 0.0
  box_orientation_w: 1.0
- scene_name: 'bag_dispenser'
  frame_id: 'world'
  box_x_dimension: 0.4
  box_y_dimension: 0.4
  box_z_dimension: 0.4
  box_position_x: 0.0
  box_position_y: 0.95
  box_position_z: 1.2
  box_orientation_x: 0.0
  box_orientation_y: 0.0
  box_orientation_z: 0.0
  box_orientation_w: 1.0
- scene_name: 'camera'
  frame_id: 'world'
  box_x_dimension: 0.1
  box_y_dimension: 0.05
  box_z_dimension: 1.95
  box_position_x: 0.85
  box_position_y: -1.03
  box_position_z: 0.975
  box_orientation_x: 0.0
  box_orientation_y: 0.0
  box_orientation_z: 0.0
  box_orientation_w: 1.0
